AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Nested Stack Resources


Resources:
  NestedFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: app.handler
      CodeUri: src/nested_lambda_function
      Description: This is an example of a nested lambda function

Outputs:
  NestedFunctionOutput:
    Description:  Output the ARN of the Nested Function
    Value: !GetAtt NestedFunction.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "NestedFunction"]]